theme: jekyll-theme-merlot
show_downloads: [true]
title: [Thank You !]
description: [Thanks for visiting my project in Technosium 2K23 @ SKI]
google_analytics: [G-8QZNN6NFYT]

github:
  zip_url: https://my-ski-projects.github.io/number-detective/
  tar_url: https://my-ski-projects.github.io/number-detective/
  owner_url: https://my-ski-projects.github.io/number-detective/
  repository_url: https://my-ski-projects.github.io/number-detective/
  owner_name: "Kanishka S"
